/** Default catalog — seeded on first run if database is empty */
export const SEED_PRODUCTS = [
  {
    id: 'ot-table-1201',
    categoryId: 'general',
    name: '1201 C-ARM Compatible Electric OT Table',
    subtitle: 'Model 1201 · Electric Operating Table',
    tagline: 'Five-sectional radiolucent top for seamless C-arm imaging',
    price: 125000,
    priceNote: 'GST and transport extra',
    photo: '/machines/ot-table-1201.png',
    image: 'ot-table',
    badge: 'New',
    published: true,
    specs: {
      Model: '1201',
      Material: '304 Medical Grade Stainless Steel',
      'Table Length': '2000 mm',
      'Table Width': '540 mm',
      'Min Height (without mattress)': '750 mm',
      'Max Height (without mattress)': '1000 mm',
      'Trendelenburg / Reverse': '25° / 25°',
      'Lateral Tilt': '±20°',
      'Back Section': '±60°',
      'Head Section': '±60°',
      'Leg Section': '0° – 90°',
      'Floor Locking': 'Manual',
      'Top Sections': '5 (Radio-translucent)',
      'Battery Backup': 'Standby with recharging circuit',
      Optional: 'Low Height · Remote Floor Lock · Manual Override',
    },
    description:
      'The Model 1201 is a C-ARM compatible electric operating table built with 304 medical grade stainless steel. Features an eccentric pillar design, detachable head, leg and pelvic sections, in-built kidney bridge, and a five-sectional radio-translucent top for uninterrupted fluoroscopy. Sophisticated mechanics provide smooth, stepless articulation for precise patient positioning — including height adjustment, lateral tilt, Trendelenburg, reverse Trendelenburg, flex and reflex positions. Includes standby battery backup with recharging circuit.',
    parts: [
      { id: 'ot1201-unit', name: '1201 Electric OT Table (Complete Unit)', price: 125000, sku: 'OT1201' },
    ],
  },
  {
    id: 'ot-table-1202',
    categoryId: 'general',
    name: '1202 C-ARM Compatible Hydraulic OT Table',
    subtitle: 'Model 1202 · Hydraulic Operating Table',
    tagline: 'Reliable hydraulic positioning for every surgical procedure',
    price: 84000,
    priceNote: 'GST and transport extra',
    photo: '/machines/ot-table-1202.png',
    image: 'ot-table',
    badge: 'New',
    published: true,
    specs: {
      Model: '1202',
      Type: 'Hydraulic',
      Material: '304 Medical Grade Stainless Steel',
      'Table Length': '2000 mm',
      'Table Width': '540 mm',
      'Min Height (without mattress)': '750 mm',
      'Max Height (without mattress)': '1000 mm',
      'Trendelenburg / Reverse': '25° / 25°',
      'Lateral Tilt': '±20°',
      'Back Section': '±70°',
      'Head Section': '±60°',
      'Leg Section': '0° – 90°',
      'Floor Locking': 'Manual',
      'Top Sections': '5 (Radio-translucent)',
    },
    description:
      'The Model 1202 is a C-ARM compatible hydraulic operating table crafted from 304 medical grade stainless steel. Built with eccentric pillars and stainless fittings, it features detachable head, leg and pelvic sections, an in-built kidney bridge, and a five-sectional radio-translucent top for seamless fluoroscopy. The attractive, easy-to-clean stainless steel base and cover house sophisticated hydraulic mechanics that deliver smooth, stepless articulation for precise patient positioning.',
    parts: [
      { id: 'ot1202-unit', name: '1202 Hydraulic OT Table (Complete Unit)', price: 84000, sku: 'OT1202' },
    ],
  },
]
